### ISSUE TITLE
Don't limit yourself as a coder

### ISSUE THREAD

**Issue by CatTail** [metrue/nice-place-for-coding#3]
Even you are a programmer, you shouldn't bind anything with GitHub. A more suitable way to do the job maybe foursquare or "街旁“.

**Comment by metrue** [comment]
@CatTail 
You're right. but for this case, I think GitHub is the simplest way to get thing done, since what we need is good place for coding.  

Maybe be a place which is good for coding is good for doing the other things. then we can make this list hosted on a more common place, like you suggest, foursquare or "街旁"
